name: Installation Step of Release Process
on:
  pull_request:

env:
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  IS_PR: ${{ github.event_name == 'pull_request' }}
  IS_WEEKLY: ${{ github.event_name == 'schedule' }}
  IS_RELEASE: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
  IS_PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
  RUNNER_TOOL_CACHE: /opt/hostedtoolcache

jobs:
  package-release:

    name: Package and artifacts release
    runs-on: ubuntu-20.04

    env:
      PRIVATE_RELEASE_IMAGE_BASE: ghcr.io/zama-ai/concrete-numpy
      PUBLIC_RELEASE_IMAGE_BASE: zamafhe/concrete-numpy

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      # See #570 To be updated to only install required dependencies group with poetry 1.2 and
      # remove graphviz installs which are only required for the actual package and not dev tools
      - name: Install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y graphviz*
          sudo apt-get install --no-install-recommends -y gnome-keyring
          python -m pip install --upgrade pip
          python -m pip install poetry
          make setup_env
